export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST';

export const PRODUCT_EDIT_FAIL = 'PRODUCT_EDIT_FAIL';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_REQUEST = 'PRODUCT_EDIT_REQUEST';

export const PRODUCT_REMOVE_FAIL = 'PRODUCT_REMOVE_FAIL';
export const PRODUCT_REMOVE_SUCCESS = 'PRODUCT_REMOVE_SUCCESS';
export const PRODUCT_REMOVE_REQUEST = 'PRODUCT_REMOVE_REQUEST';

export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';

export const PRODUCT_UNIT_ADD_REQUEST = 'PRODUCT_UNIT_ADD_REQUEST';
export const PRODUCT_UNIT_ADD_SUCCESS = 'PRODUCT_UNIT_ADD_SUCCESS';
export const PRODUCT_UNIT_ADD_FAIL = 'PRODUCT_UNIT_ADD_FAIL';

export const TAKEOFF_LIST_REQUEST = 'TAKEOFF_LIST_REQUEST';
export const TAKEOFF_LIST_SUCCESS = 'TAKEOFF_LIST_SUCCESS';
export const TAKEOFF_LIST_FAIL = 'TAKEOFF_LIST_FAIL';

export const TAKEOFF_ADD_REQUEST = 'TAKEOFF_ADD_REQUEST';
export const TAKEOFF_ADD_SUCCESS = 'TAKEOFF_ADD_SUCCESS';
export const TAKEOFF_ADD_FAIL = 'TAKEOFF_ADD_FAIL';
 